# This is a basic workflow to help you get started with Actions

name: build latex to pdf

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: get date
        id: date
        run: |
          echo "date=$(date +'%Y %b') " >> $GITHUB_OUTPUT

      - name: compile latex
        uses: xu-cheng/latex-action@3.2.0
        with:
          root_file: main.tex

      - name: rename pdf
        run: mv main.pdf DylanChua_CV.pdf

      - name: create tag
        id: tag
        run: |
          TAG=$(date +'%Y-%m')
          echo "tag=$TAG" >> $GITHUB_OUTPUT 
          git tag $TAG ${GITHUB_SHA}
          git push origin $TAG

      - name: create release
        uses: softprops/action-gh-release@v2.0.8
        with:
          name: ${{ steps.date.outputs.date }}
          tag_name: ${{ steps.tag.outputs.tag }}
          files: DylanChua_CV.pdf
